### ISSUE TITLE
Unsupported attributes for PyVISA-py TCPIP SOCKET communication

### ISSUE THREAD

**Issue by MatthieuDartiailh** [pyvisa/pyvisa-py#109]
First reported on PyVisa: https://github.com/pyvisa/pyvisa/issues/274

**Comment by skrchnavy** [comment]
@cwgamma 
I checked documentation for NI: http://zone.ni.com/reference/en-XX/help/370131S-01/ni-visa/vi_attr_send_end_en/
`VI_ATTR_SEND_END_EN` is not valid for TCPIP SOCKET only for TCPIP INSTR.

Anyway, it works as you have written, I tested it using pyvisa shell with backend pyvisa-py, attribute is supported but not listed and can't be changed.

**Comment by MatthieuDartiailh** [comment]
Should we close then ?

**Comment by skrchnavy** [comment]
no, this is real issue, VI_ATTR_SEND_END_EN shall be ignored but ['VI_ATTR_SUPPRESS_END_EN'](http://zone.ni.com/reference/en-XX/help/370131S-01/ni-visa/vi_attr_suppress_end_en/) shall be implemented. I am working on it for TCPIP.

**Comment by MatthieuDartiailh** [comment]
Cool

**Comment by MatthieuDartiailh** [comment]
Closed by #114
