### ISSUE TITLE
TCPIP attribute error

### ISSUE THREAD

**Issue by Sugarsplash** [pyvisa/pyvisa-py#159]
Just recently upgraded to version 0.3.0 and I am seeing the following error:

`
 File "/local/lib/python2.7/site-packages/pyvisa-py/tcpip.py", line 181, in write
    self.link, self._io_timeout, self.lock_timeout,
AttributeError: 'TCPIPInstrSession' object has no attribute '_io_timeout'
`

**Comment by MatthieuDartiailh** [comment]
Thanks for the report and sorry for the inconvenience I will try to fix ASAP.

**Comment by MatthieuDartiailh** [comment]
Please see #160
