### ISSUE TITLE
Make sure that pyserial if present is recent enough

### ISSUE THREAD

**Issue by MatthieuDartiailh** [pyvisa/pyvisa-py#163]
cf https://github.com/pyvisa/pyvisa/issues/358

**Comment by slightlynybbled** [comment]
Was about to implement this, but it appears that the feature has already been implemented under `pyvisa-py/serial.py`, line 24-25.  Should this issue be closed?

**Comment by MatthieuDartiailh** [comment]
Thanks @slightlynibbled.
