### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by slightlynybbled** [pyvisa/pyvisa-py#187]
Under `FAQ`, and `Which libraries are used by PyVISA-py`, the links for each of the projects pyserial and pyusb are both broken.

https://pyvisa-py.readthedocs.io/en/latest/#which-libraries-are-used-by-pyvisa-py

Link to pyserial: https://pythonhosted.org/pyserial/

Link to pyusb: https://github.com/pyusb/pyusb

**Comment by MatthieuDartiailh** [comment]
As I said earlier, you are welcome to submit a PR, otherwise I should have time to fix this Wednesday evening.
