### ISSUE TITLE
gpib.py: VI_ATTR_SEND_END_EN should call IbcEOT, not the unimplemented IbcEndBitIsNormal

### ISSUE THREAD

**Issue by dirkenstein** [pyvisa/pyvisa-py#196]
This issue may be specific to using pyvisa-py with linux-gpib 4.2.0 but may not happen with NI 488.2 libararies.

Basically linux-gpib does not implement IbcEndBitIsNormal being set to 0.

However, according to the NI-488.2 documentation,  IbcEndBitIsNormal seems to relate to _receiving_ EOI not sending it.

I believe VI_ATTR_SEND_END_EN should use  IbcEOT (0x4) constant for setting send EOI or not. This is both for` ibconfig()` and `ibask()`.

**Comment by MatthieuDartiailh** [comment]
Thanks for report. If you can make a PR with those changes it would be great ! I will try to look into it but I am not very familiar with linux-gpib it may take me some time. 

As a side note, if you are familiar with low-level gpib operation, I would greatly appreciate if you have time to review https://github.com/pyvisa/pyvisa-py/pull/194 that aims at improving GPIB support in Pyvisa-py.

**Comment by MatthieuDartiailh** [comment]
Closed by #194
