### ISSUE TITLE
upgrade to Version: 0.4.0.dev0

### ISSUE THREAD

**Issue by fan-bingbing** [pyvisa/pyvisa-py#217]
I am sorry if I put this question on wrong place as I did not find a place to ask after googling...
Could you please let me know how to upgrade to pyvisa-py Version: 0.4.0.dev0?
I currently have 0.3.1 installed on one of my working PC which need to be upgraded to 0.4.0.dev0.
thanks.

**Comment by MatthieuDartiailh** [comment]
Pyvisa 0.4.0dev is not published on PyPI so you need to install directly from github using `pip install https://github.com/pyvisa/pyvisa-py/tarball/master`.

**Comment by rjollos** [comment]
Will you be publishing 0.4 to PyPI?

**Comment by MatthieuDartiailh** [comment]
Done. Sorry I messed up the upload (wrong credentials and I missed the message).
