### ISSUE TITLE
[COM] Communication issue with XXX using XXX

### ISSUE THREAD

**Issue by 32nguyen** [pyvisa/pyvisa-py#220]
Dear Pyvisa development team, 

Is Pyvisa safe with multiple-process use? I have several instruments that had to control using threads.

Bests,

Thanh

**Comment by MatthieuDartiailh** [comment]
You can use pyvisa in a multithreaded environment yes but you should ensure manually that two threzd do not talk to the same instrument from different thread at the same time.
