### ISSUE TITLE
[COM] Communication issue with pyvisa-py backend for remote NI resource

### ISSUE THREAD

**Issue by Vanguo996** [pyvisa/pyvisa-py#304]
```  
  "Could not parse %s: unknown interface type" % resource_name
pyvisa.rname.InvalidResourceName: Could not parse visa://192.168.1.108/GPIB0::7::INSTR: unknown interface type
```

i use pyvisa-py backend 
is there any solution for supporting remote ni resource ?  

thanks! 

ps: i want to run mesurement program in docker container

**Comment by MatthieuDartiailh** [comment]
Generally PyVISA does not support parsing remote VISA resource names, but there could be workaround. However I have no idea how remote VISA works (and I have not found documentation by IVI referring to remote VISA implementation, the VISA specification does not discuss it much https://www.ivifoundation.org/downloads/Architecture%20Specifications/vpp43_2020-11-20.pdf). So I do not know if we could add support for it in pyvisa-py.
