### ISSUE TITLE
write_binary_values fails with Python 2x

### ISSUE THREAD

**Issue by phookit** [pyvisa/pyvisa-py#94]
Calling write_binary_values with a string fails with struct conversion error on Python 2

write_binary_values(':system:setup ", "<foo>bar</foo>", datatype='B', is_big_endian=False)

In `to_ieee_block` the call to struct.pack fails (not integer) in the branch for Python < 3.

The data needs to be ord()'d before being packed.

**Comment by skrchnavy** [comment]
bytes or bytearray shall be used for such data.
```
write_binary_values(':system:setup ", b'bar', datatype='B', is_big_endian=False)
```

Anyway, this is probably issue of [pyvisa](https://github.com/pyvisa/pyvisa) project

**Comment by bilderbuchi** [comment]
I don't think Python 2 is still supported, so I think this can be closed.

**Comment by MatthieuDartiailh** [comment]
Indeed
